### ISSUE TITLE
Unable to use Break Lines in text field

### ISSUE THREAD

**Issue by FreddyCrugger** [flagrow/terms#5]
Hello,

It is impossible to use  break line <br /> in the text field causing the whole text to be added in 1 line.

Thanks

**Comment by clarkwinkelmann** [comment]
Yes, no formatting is possible as of right now.

I was considering passing the text through Flarum's TextFormatter, so all features of posts can be used there as well, including line breaks.

If you just want line breaks to work, you can add the following custom CSS to your forum:

    .Flagrow-Terms-SignUp-Legal { white-space: pre; }

Please note this CSS will also make tabs and multiple spaces visible if they are present in the text..

**Comment by clarkwinkelmann** [comment]
Going to close this issue.

I've created another issue for the "allow formatting" feature request #7
