### ISSUE TITLE
Extension removes App--discussion class from div#app

### ISSUE THREAD

**Issue by pflstr** [flagrow/terms#6]
In my installation of Flarum (moccato.de), the *terms* extension removes the `App--discussion` class from the `<div id="app">` in discussion views. Deactivating the *terms* extension restores the class.

**Comment by clarkwinkelmann** [comment]
I can replicate that. That's a strange one !

I'm going to investigate that.

**Comment by clarkwinkelmann** [comment]
Will be fixed in next release, thanks for the report !
